/*
 * This source file was generated by the Gradle 'init' task
 */
package bq.loader;

import bq.duckdb.DuckDb;
import bq.util.Config;
import bq.util.S;
import com.google.common.flogger.FluentLogger;
import java.io.File;

public class Main {

  static FluentLogger logger = FluentLogger.forEnclosingClass();

  public static void main(String[] args) {

    DuckDb db = DuckDb.getSharedInMemory();
    File f = new File(".");
    try {
      f = f.getCanonicalFile();
    } catch (Exception e) {
      f = f.getAbsoluteFile();
    }
    logger.atInfo().log("WORKDIR         : %s", f);
    logger.atInfo().log("S3_BUCKET       : %s", S3Config.getBucket());

    do {
      new MultiLoadTask(db).symbols(Config.get("SYMBOLS").orElse(null)).execute();
    } while (continueRunning());
  }

  static boolean continueRunning() {
    return S.notBlank(System.getenv("DAEMON")).orElse("false").toLowerCase().trim().equals("true");
  }
}
