/*
 * This source file was generated by the Gradle 'init' task
 */
package bq.loader;

import bq.duckdb.DuckDb;
import java.io.IOException;

class AppTest {

  void loadData() throws IOException {

    DuckDb d = DuckDb.getSharedInMemory();

    MultiLoadTask task = new MultiLoadTask(d);

    d.template()
        .query(
            c ->
                c.sql(
                    "select symbol from"
                        + " '/Users/rob/dev/public.bitquant.cloud/index-components/spx.csv'"),
            rs -> {
              return rs.getString(1).get();
            })
        .forEach(
            name -> {
              String s = "S:" + name;
              task.symbol(s.trim());
            });

    /*
        Files.asCharSource(new File("../data.bitquant.cloud/ndx.txt"), StandardCharsets.UTF_8).forEachLine(line -> {
          String ticker = line.strip();
          if (!ticker.equals("symbol") && S.isNotBlank(ticker)) {

            String symbol = "S:" + ticker;
            System.out.println(symbol);
            task.symbol(symbol);
          }
        });
    */
    task.execute();

    // DataLoader.create(d).symbols("S:ENVX").load();

    // DataLoader.create(d).symbols("I:SPX","I:NDX","I:RUT","I:DJIA").load();

    //
    // DataLoader.create(d).symbols("S:IREN","S:CIFR","S:MSTR","S:BITF","S:CLSK").writeS3(true).load();
    // DataLoader.create(d).symbols("S:RIOT","S:MSFT","S:AAPL","S:NVDA","S:SMCI","S:V","S:MC","S:X","S:TSLA").writeS3(true).load();
    // DataLoader.create(d).symbols("X:BTC","X:SOL","X:SHIB","X:ETH","X:DOGE","X:RENDER").writeS3(true).load();

  }
}
